name: Rust + Bevy CI

on:
  merge_group:
  pull_request:
    paths:
      - '**/*.rs'
      - '**/*.toml'
      - '**/*.ron'
      - 'assets/**'
      - 'src/**'
      - 'Cargo.lock'
  push:
    branches: [main]
    paths:
      - '**/*.rs'
      - '**/*.toml'
      - '**/*.ron'
      - 'assets/**'
      - 'src/**'
      - 'Cargo.lock'

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-ci-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install -y --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

      - name: Install cargo tools
        run: |
          cargo outdated --version || cargo install cargo-outdated
          cargo audit --version || cargo install cargo-audit

      - name: Security audit
        run: cargo audit

      - name: Check outdated dependencies
        run: cargo outdated -R

      - name: Check code format
        run: cargo fmt -- --check

      - name: Lint with clippy
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --verbose
